Add AddProcCommandParserTest
AY2122S2-CS2103T-W13-1/tp pull request #84
Opened 2022-03-17 19:02 UTC by jbkim1999

Also rename and restructure CommandTestUtil.java to allow better consistency when testing Procedure-related features.

2022-03-17 19:04 UTC, jbkim1999 commented on src/test/java/seedu/address/logic/commands/AddProcCommandTest.java
> +package seedu.address.logic.commands;
Still a skeletal version that is pasted from AddCommandTest.java

2022-03-19 11:26 UTC, iztanpy reviewed
Good use of comments which make it easy to understand! I think that so far addProcCommandParserTest looks good! Please ping me when addProcCommandTest is completed :)

2022-03-19 11:26 UTC, iztanpy commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> +        assertFalse(addAppleBeesCommand.equals(addBurgerCommand));
I think the shop name is Applebees so I am not sure if we should use camelcase? But if its easier for us to look at, then I think its ok too :)

2022-03-22 12:07 UTC, jbkim1999 commented
Note:

@iztanpy, I made some naming changes on `CommandTestUtil.java`, the reason is that I needed some consistency regarding which Date and/or Cost refers to which Procedure (repair or replace?). This will make more sense when you take a look at your `ProcedureTest.java`!

@teominghuang, you might want to take a look at my tests since you are writing for deleteProc as well, I believe these two can be quite similar in terms of testing!

@aceszhenwei, you can consider how I structure my tests when you want to test the auto-sort feature for AddProc as well!

2022-03-23 13:17 UTC, teominghuang requested changes
Overall, very well done testing. I see that there has been improvement in terms of your coding standard, better abstraction, better adherence to coding styles, and I am very happy for you! Just some tiny tweaks here and there in bettering coding readability! :)

2022-03-23 13:17 UTC, teominghuang commented on src/test/java/seedu/address/logic/commands/AddProcCommandTest.java
> +                .withProcedures(addProcCommand.procListWithAddedProperProc(clientToAddProc.getProcedures())).build();
Good abstraction thus far, but I think it would be good to separate these chunks of code to increase developer's readability :), what do you think?

2022-03-23 21:56 UTC, teominghuang approved these changes
LGTM! Good work! :)

2022-03-23 21:56 UTC, merged